### ISSUE TITLE
Some improvements for your script.

### ISSUE THREAD

**Issue by walder** [RicSti/ga4-tracking-logger-chrome-extension-panel#1]
Thanks for your work, great script!

In case you are interested I added some functionality to your script, see:
https://github.com/walder/google-ads-youtube-channel-excluder

Mainly I added a check so music channels are excluded.
Also I believe your Regex exclusion in the Google Ads query does not work, I changed it to like %XXX%.
Channels explicitly set to be included in the Google Ads interface will now now longer be blacklisted they match exclusion criteria.

**Comment by RicSti** [comment]
@walder Thank you very much for your feedback! Glad to see someone using my script and even improving it. That's really cool! We actually have a lack of video campaigns but I will definitely give it a try as soon as I have a new use case for it.
